name: EcOps Script Runner
description: Start or end performance measurement using perf

inputs:
  method:
    description: 'Method to use (start_measurement, end_measurement)'
    required: true
  args:
    description: 'Extra arguments for perf (e.g., perf cpu-cycles instructions 1000)'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        echo "Ejecutando en la ruta de la acción: ${{ github.action_path }}"
        ls -la "${{ github.action_path }}"
        chmod +x "${{ github.action_path }}/setup.sh"
        "${{ github.action_path }}/setup.sh" ${{ inputs.method }} \
          "${{ github.run_id }}" \
          "${{ github.ref_name }}" \
          "${{ github.repository }}" \
          "${{ github.run_id }}" \
          "${{ github.workflow }}" \
          "${{ github.sha }}" \
          "${{ github.event_name }}" \
          ${{ inputs.args }}
      shell: bash
