name: EcOps Script Runner
description: Start or end performance measurement using perf

inputs:
  method:
    description: 'Method to use (start_measurement, end_measurement)'
    required: true
  args:
    description: 'Extra arguments for perf (e.g., perf cpu-cycles instructions 1000)'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        chmod +x "$GITHUB_ACTION_PATH/setup.sh"
        "$GITHUB_ACTION_PATH/setup.sh" ${{ inputs.method }} \
          "${{ github.run_id }}" \
          "${{ github.ref_name }}" \
          "${{ github.repository }}" \
          "${{ github.run_id }}" \
          "${{ github.workflow }}" \
          "${{ github.sha }}" \
          "${{ github.event_name }}" \
          ${{ inputs.args }}
      shell: bash

    - name: Show EcOps Markdown Report
      if: inputs.method == 'end_measurement'
      run: |
        echo "### EcOps Performance Report" >> $GITHUB_STEP_SUMMARY
        cat ecops-report.md >> $GITHUB_STEP_SUMMARY
      shell: bash

